### PR TITLE
Fixed iteritems/itervalues for SortedDicts in Python 2.7

### PR DESCRIPTION
**Pull request by adrianherrera**
`sortedcontainers v2.0.4` removed `iteritems`/`iterkeys` on `SortedDicts` (they now raise an `AttributeError` exception - see https://github.com/grantjenks/python-sortedcontainers/commit/3367ea58432ef5ee7f34ca566c3120dc2b57c4cc), which breaks the `_SortedNode` class.

Check if we are calling `iteritems` on a `SortedDict`, and if we are call `items` instead.

Alternatively, we could remove the check all together and just call `items`/`values` for all Python 2 **and** Python 3 code.

### CODE REVIEW

**Comment by gsakkis** [comment]
Thanks for the PR, looks good though I'd prefer a `hasattr/getattr` check instead of `isinstance` to be future-proof and cover more mapping classes. Would you mind updating it?

**Comment by adrianherrera** [comment]
Fixed!

**Comment by adrianherrera** [comment]
Thanks! When you get the chance, could you also please push a new version
to pypi.

Thanks again :)

**Comment by gsakkis** [comment]
New version pushed, thanks!

**Pull request merged**
